layout_spectrum: 0.5300752
typography_spectrum: 0.7749732
color:
  saturation: 0.8802363
  lightness: 0
  brandStrength: 0.7269852
  rhythmicContrast: 0.8061225
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: APlaceToCallHome  Fans
